### PR TITLE
Spruce up scripting guide

### PR DESCRIPTION
**Pull request by tigt**
- Used documentation components
- Disambiguated terms with more specific language and hyperlinks
- Marked sections where I’d like to explain more to the user with `TODO` — I could use help answering these!

### CODE REVIEW

**Comment by tkadlec** [comment]
Thanks for doing this! We had another contributor already super deep into improving this page, so we rolled his PR first. Might need to have a fresh look now to see if there's still stuffy you want to tidy here? @tigt

**Comment by tigt** [comment]
Yeah, makes sense. I also had some TODO segments that ideally might have been answered by his changes.

**Comment by tigt** [comment]
The lingering questions:

1. What character encodings/sets are allowed in script files? ASCII-only? UTF-8?
2. How does one perform the following:
   > For debugging, it is easiest to limit scripts to `navigate` and `exec`/`execAndWait` commands, which can be debugged locally in browser developer tools.
3. Since it seems like script commands are Tab-separated, how to select if the attribute value or the innerText/HTML contain that character (`\t`)?
4. Is this also true for the `for` attribute and its `.htmlFor` property, as seen on `<label>`?
   > Why not `class`? To target an element by class, you must use an attribute name of `className`, like `className=tabInputFields`.
5. The original docs capitalized its content selector as `innerHtml` — is that the correct spelling for WPT scripting, as opposed to the all-uppercase DOM property?
6. For `selectValue`, are the other elements with brower-powered option lists also supported? (`<keygen>` and/or `<datalist>`)

**Comment by tigt** [comment]
Closing as the Scripting guide has been updated frequently since this, so it’s no longer useful to merge it.

**Pull request closed without merging**
